@startuml
class UserInputEndpoint <<InputEndpoint>>
class UserInputInterpreter <<Function>>
class WrapOutput <<Function>>
class CommandLineOutputEndpoint <<OutputEndpoint>>

UserInputEndpoint --> UserInput
UserInput --> UserInputInterpreter
UserInputInterpreter --> UnknownCommand
UnknownCommand --> WrapOutput
UserInputInterpreter --> QuitCommand
QuitCommand --> WrapOutput
WrapOutput --> WrappedOutput
WrappedOutput --> CommandLineOutputEndpoint
@enduml